### ISSUE TITLE
CRI-O pause image and pause command runtime modification clashes with package defaults

### ISSUE THREAD

**Issue by saschagrunert** [SUSE/skuba#751]
Right now, the `PauseImage` derives from `skuba.ImageRepository`:
https://github.com/SUSE/skuba/blob/d69c2e894e4112cfa2c23526486ae663fd38aecd/pkg/skuba/actions/cluster/init/init.go#L62

Since skuba is not able to change the CRI-O's `pause_command` option, it could be possible to have an invalid set of configuration parameters which fails during runtime.

I see two ways to solve this:
1. Either: Don't write the CRI-O configuration in skuba any more and provide different configuration packages in IBS/OBS, which work out of the box _(preferred)_
2. Or: Add the `pause_command` option to be changed by skuba, too

What do you think?

Relates (somehow) to: https://github.com/SUSE/avant-garde/issues/858

**Comment by ereslibre** [comment]
Isn't there a third option? We could leave crio configuration untouched (unless until it supports a `crio.conf.d` configuration folder), and use a systemd drop-in unit file where we could override certain parameters (like `--pause-image` and/or `--pause-command` -- `--pause-command` wasn't added because I don't think we found anything different than `/pause`, but I might be mistaken).

Since this issue is more about `pause_command` than anything else, have we spotted on the wild this specific problem?

**Comment by saschagrunert** [comment]
> Since this issue is more about `pause_command` than anything else, have we spotted on the wild this specific problem?

The config in the [devel:kubic](https://build.opensuse.org/package/view_file/devel:kubic/cri-o/crio.conf?expand=1) package uses `/usr/bin/pause` since some time, so we discovered that possible pitfall when migrating the config to the latest changes.

**Comment by ereslibre** [comment]
Can we leave this to the entrypoint? Would `--pause-command=""` work, running the entrypoint defined in the image?

**Comment by saschagrunert** [comment]
> Can we leave this to the entrypoint? Would `--pause-command=""` work, running the entrypoint defined in the image?

Unfortunately not right now, the entrypoint will not taken into account. I follow-up on this topic on https://github.com/cri-o/cri-o/pull/2881

**Comment by chentex** [comment]
Follow up PR was merged I assume this can be closed.
https://github.com/cri-o/cri-o/pull/2881
