### ISSUE TITLE
Call zypper with `--userdata`

### ISSUE THREAD

**Issue by kkaempf** [SUSE/skuba#904]
All calls to `zypper` should pass a `--userdata` value.

https://github.com/SUSE/doc-caasp/issues/644#issuecomment-566900165 raised the question of "how can support detect that a customer did this [call `zypper` on the node manually] "wrong"?"

`zypper` has an option to pass a `transaction id`:
```
> zypper -h
  ...
    --userdata <STRING>     User defined transaction id used in history and plugins.
  ...
```
which will appear in the `zypper.log`. `skuba` could set this id to indicated "zypper was called from skuba" in the zypper.log.

**Comment by jodavis-suse** [comment]
Interesting idea.  Would we want to use a generic and common "--userdata skuba" for all calls to zypper made by skuba, or would there be additional information that could be valuable as well?

**Comment by Klaven** [comment]
just a comment. I like the idea of doing something like `--userdata skuba-[uid]` not sure what all your thoughts are on it. might be overkill/not needed or useful. was thinking if we had better logging it might help tie things together.

**Comment by jodavis-suse** [comment]
As we talked about this, it would also make sense to have separate identifiers for skuba and skuba-update and any other modules within the code base.  There are also a fair number of templates and helper scripts under the ci/ which can be reviewed too, though instances for build and testing can be skipped.

**Comment by dannysauer** [comment]
Unless we're going to have something associated with logs of the skuba / skuba-update execution itself (which the transaction ID could then be correlated against), I don't see much point in making this any sort of dynamic string. It only serves to makes "grep for all the things skuba did" and similar slightly more difficult, at that point. :)

If it's going to be something that can be tied back to other logs, on the other hand, it seems like the transaction ID should really be a "session ID" generated every time the zypper-calling command runs rather than just as part of the zypper command.

**Comment by jodavis-suse** [comment]
I think I'll go for the 'simplest possible' approach for this and use static strings.  Expect a new PR commit soon.

**Comment by jodavis-suse** [comment]
@dannysauer Both commits for this issue have now merged.  Is there a release this should get labeled for before I close the issue?

**Comment by dannysauer** [comment]
I added the 4.1.2 label to both PRs and this ticket.  I think that's all which is needed.

Before marking this closed, should there perhaps also be a note somewhere about how this data shows up in the zypper logs?  Right now, it's just tribal knowledge that skuba-triggered zypper executions contain this additional information.  Might be worth opening a separate ticket (probably in avant-garde) to document this behavior change.

**Comment by dannysauer** [comment]
Should've tagged you in that, @jodavis-suse.  Whoops.

**Comment by jodavis-suse** [comment]
Good point about adding some sort of documentation note.  It is something you would have to know to look for.  Is there also some sort of support knowledge base we could add this to?

**Comment by dannysauer** [comment]
I think Confluence is probably the most likely place for someone to look for that sort of diagnostic, borderline developer information, though I'm inclined to think it really should be embedded within the source repo here on Github.  Because Confluence isn't "open", though, I'm not sure that's really the "right" long-term solution; we should theoretically be supporting outside developers (perhaps technically-inclined customers) who might want to contribute to skuba.  I hate the idea of adding usage.md5 or similar here and having it fall out of sync with the official SUSE/caasp-doc repo, though.  Might be worth engaging @r0ckarong about ideas regarding a way to publish more technical developer- and support engineer-centric documentation in a place more than just a few people can access?

**Comment by jodavis-suse** [comment]
I see that @r0ckarong created https://confluence.suse.com/display/CaaSP/CaaSP-Troubleshooting so he can comment if that is a good place to make a note.

**Comment by jodavis-suse** [comment]
Also there is https://documentation.suse.com/suse-caasp/4.0/html/caasp-admin/_troubleshooting.html if we think it is something we want customers to see.  I don't think that is critical for this issue, and it would likely be just noise in the document.

**Comment by r0ckarong** [comment]
> I see that @r0ckarong created https://confluence.suse.com/display/CaaSP/CaaSP-Troubleshooting so he can comment if that is a good place to make a note.

This is an ancient document that I dumped from the old MicroFocus Wiki when it wasn't clear if they would stick around after the merger. I think the support people update this occasionally but I wouldn't want to be asked about its currency. Largely this was unreviewed by CaaSP before I copied it off the stone slabs.

If we want to engage external developers to contribute to skuba I think the GitHub wiki is actually a pretty good resource to tie info closely to the code without having to rely on SUSE run systems. There are plenty of considerations though what to expose, what marketing/PM wants to keep close to the chest etc.. From my experience developer docs is quite an extensive process before a single document is published. I'm happy to help if this comes to pass.

**Comment by jodavis-suse** [comment]
Which GitHub wiki are we referring to? (https://github.com/SUSE/skuba/wiki is empty)
Also, if we do have official external troubleshooting we could link it from the skuba/README.md.  I also notice the README.md doesn't link to https://documentation.suse.com/suse-caasp/4.1/, which might be useful (though I could understand a counter argument against linking to a versioned release document).

**Comment by r0ckarong** [comment]
I was suggestion to fill the GitHub wiki with developer specific info.

**Comment by jodavis-suse** [comment]
Thanks for the suggestions.  We discussed this in our Y Squad meeting this morning and José has created https://confluence.suse.com/display/CaaSP/Troubleshooting+recipes with the intent of capturing troubleshooting information now and possibly formalizing it in the future.  I've added this information there.

**Comment by jordimassaguerpla** [comment]
Is there any bsc about this?

**Comment by jodavis-suse** [comment]
No bsc that I'm aware of, and searching bugzilla did not find any relevant issues.
